"""Report generator -- produces Markdown, HTML, and JSON reports."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any


def generate_markdown_report(
    target: str,
    findings: list[dict],
    summary: dict | None = None,
) -> str:
    """Generate a Markdown report suitable for HackerOne/Bugcrowd submission."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_findings = sorted(findings, key=lambda f: severity_order.get(f.get("severity", "info"), 4))

    counts = {}
    for f in sorted_findings:
        sev = f.get("severity", "info")
        counts[sev] = counts.get(sev, 0) + 1

    lines = [
        f"# CyberHunter Security Report",
        f"",
        f"**Target:** {target}",
        f"**Date:** {now}",
        f"**Findings:** {len(findings)}",
        f"",
        "## Summary",
        "",
    ]

    for sev in ["critical", "high", "medium", "low", "info"]:
        if sev in counts:
            lines.append(f"- **{sev.upper()}**: {counts[sev]}")

    if summary:
        lines.extend([
            "",
            f"- Subdomains discovered: {summary.get('subdomains_found', 'N/A')}",
            f"- Tool calls made: {summary.get('tool_calls', 'N/A')}",
        ])

    lines.extend(["", "---", ""])

    for i, f in enumerate(sorted_findings, 1):
        sev = f.get("severity", "info").upper()
        lines.extend([
            f"## {i}. [{sev}] {f.get('title', f.get('type', 'Unknown'))}",
            "",
            f"**Type:** {f.get('type', 'N/A')}",
            f"**Severity:** {sev}",
            f"**Confidence:** {f.get('confidence', 'N/A')}%",
            f"**URL:** `{f.get('url', 'N/A')}`",
            "",
        ])

        if f.get("description"):
            lines.extend(["### Description", "", f.get("description", ""), ""])
        if f.get("evidence"):
            lines.extend(["### Evidence", "", f"```\n{f.get('evidence', '')}\n```", ""])
        if f.get("poc"):
            lines.extend(["### Proof of Concept", "", f"```bash\n{f.get('poc', '')}\n```", ""])
        if f.get("payload"):
            lines.extend(["### Payload", "", f"```\n{f.get('payload', '')}\n```", ""])

        lines.extend(["---", ""])

    lines.extend([
        "",
        "*Report generated by CyberHunter AI Bug Bounty Platform*",
    ])

    return "\n".join(lines)


def generate_json_report(
    target: str,
    findings: list[dict],
    summary: dict | None = None,
) -> str:
    report = {
        "target": target,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_findings": len(findings),
        "findings": findings,
        "summary": summary or {},
    }
    return json.dumps(report, indent=2)


def generate_html_report(
    target: str,
    findings: list[dict],
    summary: dict | None = None,
) -> str:
    md = generate_markdown_report(target, findings, summary)
    severity_colors = {
        "CRITICAL": "#dc2626",
        "HIGH": "#ea580c",
        "MEDIUM": "#ca8a04",
        "LOW": "#2563eb",
        "INFO": "#6b7280",
    }
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>CyberHunter Report - {target}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; background: #0a0a0f; color: #e2e8f0; }}
h1 {{ color: #4ade80; }}
h2 {{ border-bottom: 1px solid #1e293b; padding-bottom: 0.5rem; }}
code, pre {{ background: #1e293b; padding: 0.2rem 0.4rem; border-radius: 4px; font-size: 0.9em; }}
pre {{ padding: 1rem; overflow-x: auto; }}
hr {{ border: none; border-top: 1px solid #1e293b; margin: 2rem 0; }}
</style>
</head>
<body>
<pre>{md}</pre>
</body>
</html>"""
    return html
